### ISSUE TITLE
Copy should mirror Tracking and Leading of Sketch Doc

### ISSUE THREAD

**Issue by Thinkinggood** [potpiedigital/beckybosshart.com#7]
Downloaded a measure tool. Will send a spec sheet that includes leading, margins, font sizes.

**Comment by mysterycommand** [comment]
@Thinkinggood we could really use this speck sheet. For starters @Purple906:
- [x] The "READ ME" (`h5`) should have `letter-spacing: 4px;` and `line-height: 0.9;`
- [x] `h6`s should be `color: /* whatever that orange is */; font-size: 16px; font-weight: normal;` (also, can you get rid of those inner `span` elements? It doesn't look like their doing anything anymore)
- [x] `h4`s should be `color: #000; font-size: 14px; font-weight: bold;`

**Comment by Purple906** [comment]
done!
